DATA_NAME: "In"
DATA_PATH: "data/Indian_Pines/Indian_pines_corrected.mat"
LABEL_PATH: "data/Indian_Pines/Indian_pines_gt.mat"

MODEL_PATH: "checkpoints_in"
MODEL_PATH_TEST: "checkpoints_in/dbnn_epoch_200.pth"
FIGURE_DIR: "outputs"

PATCH_SIZE: 5
BATCH_SIZE: 32
LEARNING_RATE: 0.001
EPOCHS: 200