models:
  - name: Spectral3DCNN #3DCNN
  - name: SimpleDBNN # DNN
  - name: Simple_Resnet #ReSDBNN
  - name: DBNN_multinn # DBNN-multinn
  - name: DBNN_noTrans
  - name: DBNN_noatt
  - name: DBNN_3x3
  - name: DBNN
  - name: DBNN_gf
datasets:
  - name: IP
    data_path: "data/IP/IP.mat"
    label_path: "data/IP/IP_gt.mat"
    model_path: "checkpoints/IP"
    figure_dir: "outputs/IP"

  # - name: PU
  #   data_path: "data/PU/PU.mat"
  #   label_path: "data/PU/PU_gt.mat"
  #   model_path: "checkpoints/PU"
  #   figure_dir: "outputs/PU"
    
  # - name: KSC
  #   data_path: "data/KSC/KSC.mat"
  #   label_path: "data/KSC/KSC_gt.mat"
  #   model_path: "checkpoints/KSC"
  #   figure_dir: "outputs/KSC"

patch_size: 5
batch_size: 32
learning_rate: 0.001
max_epochs: 1500
n_components: 30
use_pca: True
model_epochs_file: "configs/model_epochs.yaml"